version: 2

project_name: pathosd

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pathosd
    main: ./cmd/pathosd
    binary: pathosd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.Commit}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X github.com/prometheus/common/version.Branch={{.Tag}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

dockers:
  - image_templates:
      - "ghcr.io/vooon/pathosd:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: amd64
  - image_templates:
      - "ghcr.io/vooon/pathosd:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/vooon/pathosd:{{ .Version }}"
    image_templates:
      - "ghcr.io/vooon/pathosd:{{ .Version }}-amd64"
      - "ghcr.io/vooon/pathosd:{{ .Version }}-arm64"
  - name_template: "ghcr.io/vooon/pathosd:latest"
    image_templates:
      - "ghcr.io/vooon/pathosd:{{ .Version }}-amd64"
      - "ghcr.io/vooon/pathosd:{{ .Version }}-arm64"
